replicaCount: 1

image:
  repository: bitnami/matomo
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""
matomoUsername:
matomoPassword:
matomoEmail:

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
  #  - matomo.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
volumeClaim:
  enabled: true
  # Reuse existing claim: (if empty, a new PVC will be created)
  existingClaim:
  accessModes:
    - ReadWriteMany
  size: 1Gi
  # Specific storage class (if empty, the cluster default will be used)
  storageClass:

smtp:
  enabled: false
  ##
  # Available variables for SMTP configuration :
  ##
  # host: e.g "smtp.gmail.com"
  host:
  # protocol: "ssl" or "tls"
  protocol:
  # port: e.g "587"
  port:
  # User and Password can be added in "smtp-user" and "smtp-password" in a secret file (see .Values.existingSecret)

readinessProbe: {}
#  initialDelaySeconds: 60
#  failureThreshold: 6
#  periodSeconds: 20
#  httpGet:
#    port: http
#    path: /index.php?module=API&method=API.getHeaderLogoUrl

livenessProbe: {}
#  initialDelaySeconds: 60
#  httpGet:
#    port: http
#    path: /piwik.php

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}

# extraInitContainers: Specifies a template string for a initContainer.
# Usecases include situations when you need some pre-run setup
extraInitContainers:
# - name: do-something
#   image: busybox
#   command: ['do', 'something']

##
# Add additional config and secrets (as key-value yaml)
#
# These are not automatically mounted in the container, you have to adapt it to your special case using
# extraEnv or extraVolumes for example.
#
# Helm template syntax will be interpreted.
##
extraConfig: {}
#  custom-config: value-{{ .Release.Name }}
extraSecrets: {}
# common.config.ini.php: |
#   ; <?php exit; ?> DO NOT REMOVE THIS LINE
#   [General]
#   {{- if .Values.ingress.enabled }}
#   {{- range .Values.ingress.hosts }}
#   trusted_hosts[]={{ . }}
#   {{- end }}
#   {{- end }}


# Configure additional environment variables for the Matomo containers.
# Helm template syntax will be interpreted.
extraEnv: |
#  - name: MATOMO_WEBSITE_HOST
#    value: {{ index .Values.ingress.hosts 1 }}

##
# Add additional volumes and mounts possibilities, for advanced use-cases.
# Helm template syntax will be interpreted.
##
extraVolumes: |
#   - name: config
#     configMap:
#       name: {{ include "matomo.fullname" . }}-external-configmap
extraVolumeMounts: |
#   - name: config
#     mountPath: /etc/cron.daily/01-daily-tasks
#     subPath: daily-tasks

mariadb:
  ## Switch to either deploy mariaDB as part of the chart, or use an external MariaDB instance :
  ## (external mariadb requires mariadb.db.host and mariadb.db.port to be set)
  deployChart: true
  db:
    ## Database to create
    ## ref: https://github.com/bitnami/bitnami-docker-mariadb#creating-a-database-on-first-run
    ##
    name: matomo_db
    user: matomo_user
    # password:

    # Only used when internal MariaDB is disabled (mariadb.deployChart=false)
    host: mariadb.example.com
    port: 3306
  service:
    port: 3306
  replication:
    enabled: false
  master:
    persistence:
      size: 5Gi
    config: |-
      [mysqld]
      skip-name-resolve
      explicit_defaults_for_timestamp
      basedir=/opt/bitnami/mariadb
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      tmpdir=/opt/bitnami/mariadb/tmp
      max_allowed_packet=128M
      bind-address=0.0.0.0
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
      log-error=/opt/bitnami/mariadb/logs/mysqld.log
      character-set-server=UTF8
      collation-server=utf8_general_ci
      [client]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      default-character-set=UTF8
      [manager]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
