{{- if or .Values.extraConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matomo.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "matomo.name" . }}
    helm.sh/chart: {{ include "matomo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{ tpl ( toYaml .Values.extraConfig ) . | nindent 2 }}
...
{{- end }}
