apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "matomo.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "matomo.name" . }}
    helm.sh/chart: {{ include "matomo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "matomo.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "matomo.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      volumes:
        {{- if .Values.volumeClaim.enabled }}
        - name: shared-data
          persistentVolumeClaim:
            claimName: {{ .Values.volumeClaim.existingClaim | default (include "matomo.fullname" .) }}
        {{- end }}
        {{- if .Values.extraVolumes }}
        {{- tpl .Values.extraVolumes . | nindent 8 }}
        {{- end }}
      {{- if .Values.extraInitContainers }}
      initContainers:
        {{- tpl .Values.extraInitContainers . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MATOMO_DATABASE_HOST
              value: {{ .Values.mariadb.deployChart | ternary (printf "%s-mariadb" .Release.Name) .Values.mariadb.db.host }}
            - name: MATOMO_DATABASE_PORT_NUMBER
              value: !!string {{ .Values.mariadb.deployChart | ternary .Values.mariadb.service.port .Values.mariadb.db.port }}
            - name: MATOMO_DATABASE_NAME
              value: {{ .Values.mariadb.db.name }}
            - name: MATOMO_DATABASE_USER
              value: {{ .Values.mariadb.db.user }}
            - name: MATOMO_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mariadb.deployChart | ternary (include "matomo.mariasecret" .) (include "matomo.fullname" .) }}
                  key: mariadb-password
            {{- if .Values.matomoEmail }}
            - name: MATOMO_EMAIL
              value: {{ .Values.matomoEmail | quote }}
            {{- end }} 
            {{- if .Values.matomoUsername }}
            - name: MATOMO_USERNAME
              value: {{ .Values.matomoUsername | quote }}
            {{- end }}
            {{- if .Values.matomoPassword }}
            - name: MATOMO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "matomo.fullname" . }}
                  key: MATOMO_PASSWORD
            {{- end }}
          {{- if .Values.smtp.enabled }}
            {{- if .Values.smtp.protocol }}
            - name: SMTP_PROTOCOL
              value: {{ .Values.smtp.protocol | quote }}
            {{- end }}
            {{- if .Values.smtp.host }}
            - name: SMTP_HOST
              value: {{ .Values.smtp.host | quote }}
            {{- end }}
            {{- if .Values.smtp.port }}
            - name: SMTP_PORT
              value: {{ .Values.smtp.port | quote }}
            {{- end }}
            {{- if .Values.smtp.auth }}
            - name: SMTP_AUTH
              value: {{ .Values.smtp.auth | quote }}
            {{- end }}
            {{- if .Values.existingSecret }}
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: smtp-user
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: smtp-password
            {{- end }}
          {{- end }}
          {{- if .Values.extraEnv }}
            {{ tpl .Values.extraEnv . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort | quote }}
              protocol: TCP
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.volumeClaim.enabled }}
            - mountPath: /bitnami
              name: shared-data
            {{- end }}
            {{- if .Values.extraVolumeMounts }}
            {{ tpl .Values.extraVolumeMounts . | nindent 12 }}
            {{- end }}
{{- include "matomo.imagePullSecrets" . | indent 6 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
