name: Chart CI

on: [push, pull_request]

jobs:
  testing:
    name: Test
    runs-on: ubuntu-latest
    container: quay.io/helmpack/chart-testing:v3.3.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          path: matomo
      - name: Lint chart
        run: cd $(dirname ${GITHUB_WORKSPACE}) && ct lint --config matomo/config.yaml
